FROM php:8.2

RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg ca-certificates debian-archive-keyring \
 && rm -rf /var/lib/apt/lists/*


RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin --filename=composer

WORKDIR /app/backend
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
